site_name: livecoding.michelepasin.org
site_description: Thoughts and ramblings about livecoding
copyright: Copyright &copy; 2022 Michele Pasin
repo_url: https://github.com/lambdamusic/The-Musical-Code

dev_addr: 127.0.0.1:8002
docs_dir: site
site_dir: ../docs

extra_css:
  - stylesheets/extra.css

nav:
  - ...

theme:
  custom_dir: overrides
  name: material
  font: false
  icon:
    logo: material/home
  # Light and Dark Theme Toggle
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lambdamusic
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/lambdamusic
    - icon: material/email
      link: https://docs.google.com/forms/d/e/1FAIpQLSc5YTPeA3LzK75sWqHYYZCXciwILDcI_sbAorM-v5sPTQmQjQ/viewform?embedded=true
  blog:
    dir: archive
    author: Michele Pasin
    # author_image: https://avatars.githubusercontent.com/u/93479011
    words_read_per_minute: 200
    list_length: 10
    extended_preview: false

markdown_extensions:
  - toc:
      title: On this page
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - meta
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - awesome-pages