# awesome-pages copy of YAML settings
# pages are loaded dynamically

site_name: The Musical Code | Experiments in Algorithmic Composition
docs_dir: src
site_dir: ../docs

repo_url: https://github.com/lambdamusic/The-Musical-Code

nav:
    - Home: index.md
    - ...

theme:
    name: material
    favicon: assets/images/favicon.ico
    logo: assets/images/logo.jpg
    custom_dir: src/assets/custom_theme/
    palette:
      scheme: default
      primary: blue
      accent: deep orange
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.path
      - content.code.copy
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
plugins:
    - search
    - awesome-pages
    - git-revision-date
    - enumerate-headings:
        toc_depth: 6
        strict: true
        increment_across_pages: false
        exclude:
          - index.md
          - about.md
          - if-you-need-to/test.md
    - print-site:
        add_to_navigation: false
        print_page_title: 'Print The Musical Code Site'
extra_javascript:
    - assets/js/headings-fix.js          
extra:
  analytics:
    provider: google
    property: GA-302041842
copyright: © Copyright 2024 Michele Pasin | <a href="https://www.michelepasin.org/about/index.html">About</a> | <a href="https://www.michelepasin.org/contact.html">Contact</a> 